/**
 Create the icons css file
 Run this script with Rhino
 */
var data = [
  {
    "cssClass":"osmBench",
    "icon":"letter_b.png"
  },
  {
    "cssClass":"osmPostbox",
    "icon":"letter_p.png"
  },
  {
    "cssClass":"osmPostoffice",
    "icon":"postal.png"
  },
  {
    "cssClass":"osmPharmacy",
    "icon":"medicalstore.png"
  },
  {
    "cssClass":"osmToilets",
    "icon":"toilets.png"
  },
  {
    "cssClass":"osmPolice",
    "icon":"police.png"
  },
  {
    "cssClass":"osmATM",
    "icon":"atm-2.png"
  },
  {
    "cssClass":"osmFuel",
    "icon":"fillingstation.png"
  },
  {
    "cssClass":"osmSchool",
    "icon":"school.png"
  },
  {
    "cssClass":"osmUniversity",
    "icon":"university.png"
  },
  {
    "cssClass":"osmBicycleparking",
    "icon":"parking_bicycle-2.png"
  },
  {
    "cssClass":"osmBicyclerental",
    "icon":"number_1.png"
  },
  {
    "cssClass":"osmTaxi",
    "icon":"taxi.png"
  },
  {
    "cssClass":"osmParking",
    "icon":"parkinggarage.png"
  },
  {
    "cssClass":"osmArtscentre",
    "icon":"artgallery.png"
  },
  {
    "cssClass":"osmTheatre",
    "icon":"theater.png"
  },
  {
    "cssClass":"osmCinema",
    "icon":"cinema.png"
  },
  {
    "cssClass":"osmInformation",
    "icon":"information.png"
  },
  {
    "cssClass":"osmMuseum",
    "icon":"museum_art.png"
  },
  {
    "cssClass":"osmArtwork",
    "icon":"number_2.png"
  },
  {
    "cssClass":"osmGallery",
    "icon":"artgallery.png"
  },
  {
    "cssClass":"osmPicnic",
    "icon":"picnic-2.png"
  },
  {
    "cssClass":"osmZoo",
    "icon":"zoo.png"
  },
  {
    "cssClass":"osmViewpoint",
    "icon":"sight-2.png"
  },
  {
    "cssClass":"osmAttraction",
    "icon":"letter_a.png"
  },
  {
    "cssClass":"osmHotel",
    "icon":"hotel_0star.png"
  },
  {
    "cssClass":"osmApartment",
    "icon":"apartment-3.png"
  },
  {
    "cssClass":"osmGuesthouse",
    "icon":"bed_breakfast1-2.png"
  },
  {
    "cssClass":"osmHostel",
    "icon":"hostel_0star.png"
  },
  {
    "cssClass":"osmMotel",
    "icon":"motel-2.png"
  },
  {
    "cssClass":"osmCampsite",
    "icon":"camping-2.png"
  },
  {
    "cssClass":"osmSoccer",
    "icon":"soccer.png"
  },
  {
    "cssClass":"osmUsFootball",
    "icon":"usfootball.png"
  },
  {
    "cssClass":"osmGolf",
    "icon":"golfing.png"
  },
  {
    "cssClass":"osmTennis",
    "icon":"tennis.png"
  },
  {
    "cssClass":"osmVolleybal",
    "icon":"volleyball.png"
  },
  {
    "cssClass":"osmBaseball",
    "icon":"baseball.png"
  },
  {
    "cssClass":"osmBasketball",
    "icon":"basketball.png"
  },
  {
    "cssClass":"osmIcehockey",
    "icon":"icehockey.png"
  },
  {
    "cssClass":"osmHockey",
    "icon":"hockey.png"
  },
  {
    "cssClass":"osmCycling",
    "icon":"cycling.png"
  },
  {
    "cssClass":"osmHorseracing",
    "icon":"horseriding.png"
  },
  {
    "cssClass":"osmSwimming",
    "icon":"swimming.png"
  },
  {
    "cssClass":"osmSurfing",
    "icon":"surfing.png"
  },
  {
    "cssClass":"osmGymnastics",
    "icon":"indoor-arena.png"
  },
  {
    "cssClass":"osmMall",
    "icon":"mall.png"
  },
  {
    "cssClass":"osmShop",
    "icon":"letter_s.png"
  },
  {
    "cssClass":"osmDepartmentstore",
    "icon":"departmentstore.png"
  },
  {
    "cssClass":"osmClothes",
    "icon":"clothers_male.png"
  },
  {
    "cssClass":"osmFashion",
    "icon":"clothers_female.png"
  },
  {
    "cssClass":"osmJewelry",
    "icon":"jewelry.png"
  },
  {
    "cssClass":"osmLeather",
    "icon":"bags.png"
  },
  {
    "cssClass":"osmShoes",
    "icon":"shoes.png"
  },
  {
    "cssClass":"osmHairdresser",
    "icon":"barber.png"
  },
  {
    "cssClass":"osmBeauty",
    "icon":"beautysalon.png"
  },
  {
    "cssClass":"osmCosmetics",
    "icon":"perfumery.png"
  },
  {
    "cssClass":"osmChemist",
    "icon":"chemistry-2.png"
  },
  {
    "cssClass":"osmOpticien",
    "icon":"ophthalmologist.png"
  },
  {
    "cssClass":"osmBooks",
    "icon":"library.png"
  },
  {
    "cssClass":"osmPhoto",
    "icon":"photography.png"
  },
  {
    "cssClass":"osmToys",
    "icon":"toys.png"
  },
  {
    "cssClass":"osmGift",
    "icon":"gifts.png"
  },
  {
    "cssClass":"osmBicycle",
    "icon":"bicycle_shop.png"
  },
  {
    "cssClass":"osmMusicalinstruments",
    "icon":"music.png"
  },
  {
    "cssClass":"osmRestaurant",
    "icon":"restaurant.png"
  },
  {
    "cssClass":"osmBar",
    "icon":"bar.png"
  },
  {
    "cssClass":"osmCafe",
    "icon":"cafetaria.png"
  },
  {
    "cssClass":"osmPub",
    "icon":"bar.png"
  },
  {
    "cssClass":"osmIcecream",
    "icon":"icecream.png"
  },
  {
    "cssClass":"osmFastfood",
    "icon":"fastfood.png"
  },
  {
    "cssClass":"osmSupermarket",
    "icon":"supermarket.png"
  },
  {
    "cssClass":"osmBakery",
    "icon":"bread.png"
  },
  {
    "cssClass":"osmConfectionery",
    "icon":"candy.png"
  },
  {
    "cssClass":"osmDeli",
    "icon":"patisserie.png"
  },
  {
    "cssClass":"osmDairy",
    "icon":"milk_and_cookies.png"
  },
  {
    "cssClass":"osmCheese",
    "icon":"cheese.png"
  },
  {
    "cssClass":"osmGreengrocer",
    "icon":"fruits.png"
  },
  {
    "cssClass":"osmGrocery",
    "icon":"grocery.png"
  },
  {
    "cssClass":"osmButcher",
    "icon":"butcher-2.png"
  },
  {
    "cssClass":"osmCoffee",
    "icon":"coffee.png"
  },
  {
    "cssClass":"osmSeafood",
    "icon":"restaurant_fish.png"
  },
  {
    "cssClass":"osmOrganic",
    "icon":"restaurant_vegetarian.png"
  },
  {
    "cssClass":"osmDrinkingwater",
    "icon":"drinkingwater.png"
  },
  {
    "cssClass":"osmAlcohol",
    "icon":"liquor.png"
  },
  {
    "cssClass":"osmWine",
    "icon":"winebar.png"
  },
  {
    "cssClass":"osmBeverages",
    "icon":"bar_coktail.png"
  },
  {
    "cssClass":"osmTravelagency",
    "icon":"travel_agency.png"
  },
  {
    "cssClass":"osmCopyshop",
    "icon":"printer-2.png"
  },
  {
    "cssClass":"osmDefibrilator",
    "icon":"aed-2.png"
  },
  {
    "cssClass":"osmFirehose",
    "icon":"fireexstinguisher.png"
  },
  {
    "cssClass":"osmMemorial",
    "icon":"memorial.png"
  },
  {
    "cssClass":"osmMonument",
    "icon":"monument.png"
  },
  {
    "cssClass":"osmWindmill",
    "icon":"windmill-2.png"
  },
  {
    "cssClass":"osmWatermill",
    "icon":"watermill-2.png"
  }
];
var i=0;
for (i=0; i<data.length; i++) {
  var css = data[i];
  print('.jstree-default .' + css.cssClass +' .jstree-themeicon {');
  print('  background-image: url("../img/markers/' + css.icon + '");');
  print('  background-position: -3px -3px;');
  print('}\n');
}





