'use strict';
function osmlConfig(osml) {
  osml.addLayer("osmBench","Bench","amenity=bench","letter_b.png");
  osml.addLayer("osmPostbox","Post box","amenity=post_box","letter_p.png");
  osml.addLayer("osmPostoffice","Post office","amenity=post_office","postal.png");
  osml.addLayer("osmPharmacy","Pharmacy","amenity=pharmacy","medicalstore.png");
  osml.addLayer("osmToilets","Toilets","amenity=toilets","toilets.png");
  osml.addLayer("osmPolice","Police","amenity=police","police.png");
  osml.addLayer("osmATM","ATM","[amenity=atm],[amenity=bank][atm][atm!=no]","atm-2.png");
  osml.addLayer("osmFuel","Fuel","amenity=fuel","fillingstation.png");
  osml.addLayer("osmSchool","School/College","[amenity=school],[amenity=college]","school.png");
  osml.addLayer("osmUniversity","University","amenity=university","university.png");
  osml.addLayer("osmBicycleparking","Bicycle parking","amenity=bicycle_parking","parking_bicycle-2.png");
  osml.addLayer("osmBicyclerental","Bicycle rental","amenity=bicycle_rental","number_1.png");
  osml.addLayer("osmTaxi","Taxi","amenity=taxi","taxi.png");
  osml.addLayer("osmParking","Parking","amenity=parking","parkinggarage.png");
  osml.addLayer("osmArtscentre","Arts centre","amenity=arts_centre","artgallery.png");
  osml.addLayer("osmTheatre","Theatre","amenity=theatre","theater.png");
  osml.addLayer("osmCinema","Cinema","amenity=cinema","cinema.png");
  osml.addLayer("osmInformation","Information","tourism=information","information.png");
  osml.addLayer("osmMuseum","Museum","tourism=museum","museum_art.png");
  osml.addLayer("osmArtwork","Artwork","tourism=artwork","number_2.png");
  osml.addLayer("osmGallery","Gallery","tourism=gallery","artgallery.png");
  osml.addLayer("osmPicnic","Picnic","tourism=picnic_site","picnic-2.png");
  osml.addLayer("osmZoo","Zoo","tourism=zoo","zoo.png");
  osml.addLayer("osmViewpoint","Viewpoint","tourism=viewpoint","sight-2.png");
  osml.addLayer("osmAttraction","Attraction","tourism=attraction","letter_a.png");
  osml.addLayer("osmHotel","Hotel","tourism=hotel","hotel_0star.png");
  osml.addLayer("osmApartment","Apartment","tourism=apartment","apartment-3.png");
  osml.addLayer("osmGuesthouse","Guest house","tourism=guest_house","bed_breakfast1-2.png");
  osml.addLayer("osmHostel","Hostel","tourism=hostel","hostel_0star.png");
  osml.addLayer("osmMotel","Motel","tourism=motel","motel-2.png");
  osml.addLayer("osmCampsite","Camp site","tourism=camp_site","camping-2.png");
  osml.addLayer("osmSoccer","Soccer","sport=soccer","soccer.png");
  osml.addLayer("osmUsFootball","American football","sport=american_football","usfootball.png");
  osml.addLayer("osmGolf","Golf","leisure=golf_course","golfing.png");
  osml.addLayer("osmTennis","Tennis","sport=tennis","tennis.png");
  osml.addLayer("osmVolleybal","Volleybal","sport=volleybal","volleyball.png");
  osml.addLayer("osmBaseball","Baseball","sport=baseball","baseball.png");
  osml.addLayer("osmBasketball","Basketball","sport=basketball","basketball.png");
  osml.addLayer("osmIcehockey","Ice hockey","[sport=ice_hockey],[leisure=ice_rink]","icehockey.png");
  osml.addLayer("osmHockey","Hockey","[sport=hockey],[sport=field_hockey]","hockey.png");
  osml.addLayer("osmCycling","Cycling","sport=cycling","cycling.png");
  osml.addLayer("osmHorseracing","Horse racing","[sport=horse_racing],[sport=equestrian]","horseriding.png");
  osml.addLayer("osmSwimming","Swimming","sport=swimming","swimming.png");
  osml.addLayer("osmSurfing","Surfing","sport=surfing","surfing.png");
  osml.addLayer("osmGymnastics","Gymnastics","sport=gymnastics","indoor-arena.png");
  osml.addLayer("osmMall","Mall/Shopping centre","shop=mall","mall.png");
  osml.addLayer("osmShop","General","shop=general","letter_s.png");
  osml.addLayer("osmDepartmentstore","Department store","shop=department_store","departmentstore.png");
  osml.addLayer("osmClothes","Clothes","shop=clothes","clothers_male.png");
  osml.addLayer("osmFashion","Fashion","shop=fashion","clothers_female.png");
  osml.addLayer("osmJewelry","Jewelry","shop=jewelry","jewelry.png");
  osml.addLayer("osmLeather","Leather","shop=leather","bags.png");
  osml.addLayer("osmShoes","Shoes","shop=shoes","shoes.png");
  osml.addLayer("osmHairdresser","Hairdresser","shop=hairdresser","barber.png");
  osml.addLayer("osmBeauty","Beauty","shop=beauty","beautysalon.png");
  osml.addLayer("osmCosmetics","Cosmetics","shop=cosmetics","perfumery.png");
  osml.addLayer("osmChemist","Chemist","shop=chemist","chemistry-2.png");
  osml.addLayer("osmOpticien","Opticien","shop=optician","ophthalmologist.png");
  osml.addLayer("osmBooks","Books/Stationary","[shop=books],[shop=stationery]","library.png");
  osml.addLayer("osmPhoto","Photo","shop=photo","photography.png");
  osml.addLayer("osmToys","Toys","shop=toys","toys.png");
  osml.addLayer("osmGift","Gift","shop=gift","gifts.png");
  osml.addLayer("osmBicycle","Bicycle","shop=bicycle","bicycle_shop.png");
  osml.addLayer("osmMusicalinstruments","Musical instruments","shop=musical_instrument","music.png");
  osml.addLayer("osmRestaurant","Restaurant","amenity=restaurant","restaurant.png");
  osml.addLayer("osmBar","Bar","amenity=bar","bar.png");
  osml.addLayer("osmCafe","Cafe","amenity=cafe","cafetaria.png");
  osml.addLayer("osmPub","Pub","amenity=pub","bar.png");
  osml.addLayer("osmIcecream","Ice cream","amenity=ice_cream","icecream.png");
  osml.addLayer("osmFastfood","Fast food","amenity=fast_food","fastfood.png");
  osml.addLayer("osmSupermarket","Supermarket","shop=supermarket","supermarket.png");
  osml.addLayer("osmBakery","Bakery","shop=bakery","bread.png");
  osml.addLayer("osmConfectionery","Chocolate/Confectionery","[shop=chocolate],[shop=confectionery]","candy.png");
  osml.addLayer("osmDeli","Deli","shop=deli","patisserie.png");
  osml.addLayer("osmDairy","Dairy","shop=dairy","milk_and_cookies.png");
  osml.addLayer("osmCheese","Cheese","shop=cheese","cheese.png");
  osml.addLayer("osmGreengrocer","Greengrocer","shop=greengrocer","fruits.png");
  osml.addLayer("osmGrocery","Grocery","shop=grocery","grocery.png");
  osml.addLayer("osmButcher","Butcher","shop=butcher","butcher-2.png");
  osml.addLayer("osmCoffee","Coffee","shop=coffee","coffee.png");
  osml.addLayer("osmSeafood","Seafood","shop=seafood","restaurant_fish.png");
  osml.addLayer("osmOrganic","Organic","shop=organic","restaurant_vegetarian.png");
  osml.addLayer("osmDrinkingwater","Drinking water","amenity=drinking_water","drinkingwater.png");
  osml.addLayer("osmAlcohol","Alcohol","shop=alcohol","liquor.png");
  osml.addLayer("osmWine","Wine","shop=wine","winebar.png");
  osml.addLayer("osmBeverages","Beverages","shop=beverages","bar_coktail.png");
  osml.addLayer("osmTravelagency","Travel agency","shop=travel_agency","travel_agency.png");
  osml.addLayer("osmCopyshop","Copy shop","shop=copyshop","printer-2.png");
  osml.addLayer("osmDefibrilator","Defibrilator/AED","emergency=defibrillator","aed-2.png");
  osml.addLayer("osmFirehose","Fire hose/extinguisher","emergency=fire_extinguisher","fireexstinguisher.png");
  osml.addLayer("osmMemorial","Memorial","historic=memorial","memorial.png");
  osml.addLayer("osmMonument","Monument","historic=monument","monument.png");
  osml.addLayer("osmWindmill","Windmill","man_made=windmill","windmill-2.png");
  osml.addLayer("osmWatermill","Watermill","man_made=watermill","watermill-2.png");
  
  osml.addLayerGroup("osmgAmenity", "Amenity", ["osmBench", "osmPostbox", "osmPostoffice", "osmPharmacy", "osmToilets", "osmPolice", "osmATM", "osmFuel", "osmSchool", "osmUniversity",
    "osmBicycleparking", "osmBicyclerental", "osmTaxi", "osmParking", "osmArtscentre", "osmTheatre", "osmCinema"]);
  osml.addLayerGroup("osmgTourism", "Tourism", ["osmInformation", "osmMuseum", "osmArtwork", "osmGallery", "osmPicnic", "osmZoo", "osmViewpoint", "osmAttraction", 
    "osmHotel", "osmApartment", "osmGuesthouse", "osmHostel", "osmMotel", "osmCampsite"]);
  osml.addLayerGroup("osmgSport", "Sport", ["osmSoccer", "osmUsFootball", "osmGolf", "osmTennis", "osmVolleybal", "osmBaseball", "osmBasketball",
    "osmIcehockey", "osmHockey", "osmCycling", "osmHorseracing", "osmSwimming", "osmSurfing", "osmGymnastics"]);
  osml.addLayerGroup("osmgShop", "Shopping",["osmSupermarket", "osmMall", "osmShop", "osmDepartmentstore", "osmClothes", "osmFashion", "osmJewelry", "osmLeather",
    "osmShoes", "osmHairdresser", "osmBeauty", "osmCosmetics", "osmChemist", "osmOpticien", "osmBooks", "osmPhoto", "osmToys", "osmGift",
    "osmBicycle", "osmMusicalinstruments"]); 
  osml.addLayerGroup("osmgFood", "Food", ["osmRestaurant", "osmBar", "osmCafe", "osmPub", "osmIcecream", "osmFastfood", "osmSupermarket", "osmBakery", "osmConfectionery", "osmDeli", "osmDairy",
    "osmCheese", "osmGreengrocer", "osmGrocery", "osmButcher", "osmCoffee", "osmSeafood", "osmOrganic", "osmDrinkingwater", "osmAlcohol", "osmWine", "osmBeverages"]);  
  osml.addLayerGroup("osmgVarious", "Various", ["osmTravelagency", "osmCopyshop", "osmDefibrilator", "osmFirehose", "osmMemorial", "osmMonument", "osmWindmill", "osmWatermill"]);
}
